### PR TITLE
fixed Createpost.jsx file

### PR DESCRIPTION
**Pull request by Dpippin09**

### CODE REVIEW

**Review by JToton — DISMISSED** [review]
This still needs to be in the file:

 const CREATE_POST_MUTATION = gql`
    mutation CreatePost($title: String!, $summary: String!, $code: String!) {
      createPost(title: $title, summary: $summary, code: $code) {
        success
        message
      }
    }
  `;

**Comment by Dpippin09** [comment]
take 2

**Review by JToton — COMMENTED** [review]
Approved but needs some adjustments.

**Comment by Dpippin09** [comment]
take 3

**Review by JToton — APPROVED** [review]
Approved, just some adjustments needed. 👍

**Pull request merged**
